import os

US_VISA_USERNAME = os.getenv("US_VISA_USERNAME")
US_VISA_PASSWORD = os.getenv("US_VISA_PASSWORD")
GMAIL_SERVER = "smtp.gmail.com"
GMAIL_PORT = 587
GMAIL_USERNAME = os.getenv("GMAIL_USERNAME")
GMAIL_PASSWORD = os.getenv("GMAIL_PASSWORD")